# Site settings
title: Brattea
description: "Indagini speziate"
url: www.brattea.net
logo4: /assets/imgindex/ # square logo
logo16: /assets/imgindex/logo16.png # narrow logo

# Author settings
author:
  name: Giorgio Spiga
  twitter: "https://twitter.com/giorgiospiga"
  email: giorgiospiga@me.com

# Nav settings
navtop: true
navbottom: false

# Pagination
paginate: 5
paginate_path: "/page:num/"
prevpage: Precedente
nextpage: Successiva
mprevpage: "&laquo;"
mnextpage: "&raquo;"

# Sass
sass:
  style: :compressed

# Handling Reading
include:      [".htaccess"]
exclude:      ["node_modules", "vendor/bundle/", "vendor/cache/", "Gemfile", "Gemfile.lock", "vendor/gems/", "vendor/ruby/", "LICENSE", "README.md", "CNAME", "Vagrantfile", ".gitignore", ".DS_Store"]

# Filtering Content
#show_drafts: null
#limit_posts: 0
#future:      false
#unpublished: false

# Plugins
#whitelist: []
gems:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-seo-tag

# Conversion
markdown:    kramdown

# Serving
#detach:  false
port:    4000
host:    127.0.0.1
baseurl:  # does not include hostname

# Outputting
permalink:     pretty
timezone:      Europe/Rome

# Services
#google_analytics: 'UA-XXXXXXXX-X'

# Post images source
imgsource: /assets/imgposts/ # Local source
#imgrsource # Remote, external source
imgdsource: https://dl.dropboxusercontent.com/u/173133/site/postimgs/

# Defaults

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      title:
      date: 2000-07-16T16:12:00+02:00
      author: gio
      coverimg:
        source:
        alt:
      tags:
