# Site settings
title: Brattea
description: "Indagini speziate"
url: https://giorgiospiga.github.io

# Author settings
author:
  name: Giorgio Spiga
  twitter: "https://twitter.com/giorgiospiga"
  email: giorgiospiga@me.com

# Nav settings
navtop: true
navbottom: false

# Pagination
paginate: 5
prevpage: Precedente
nextpage: Successiva
mprevpage: "&laquo;"
mnextpage: "&raquo;"

# Sass
sass:
  style: :compressed

# Handling Reading
include:      [".htaccess"]
exclude:      ["node_modules", "vendor/bundle/", "vendor/cache/", "Gemfile", "Gemfile.lock", "vendor/gems/", "vendor/ruby/", "LICENSE", "README.md", "CNAME", "Vagrantfile", ".gitignore", ".DS_Store"]

# Filtering Content
show_drafts: null
limit_posts: 0
future:      false
unpublished: false

# Plugins
whitelist: []
gems:
  - jekyll-paginate
  - jekyll-feed

# Conversion
markdown:    kramdown
excerpt_separator: "\n\n"

# Serving
#detach:  false
port:    4000
host:    127.0.0.1
baseurl:  # does not include hostname

# Outputting
permalink:     pretty
paginate_path: /page:num/
timezone:      Europe/Rome

# Services
#google_analytics: 'UA-XXXXXXXX-X'

# Post images source
imgsource: /assets/imgposts/ # Local source
#imgrsource # Remote, external source
imgdsource: https://dl.dropboxusercontent.com/u/173133/site/postimgs/ # Dropbox source like https://dl.dropboxusercontent.com/u/USER_ID/SOME_FOLDER/
